{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ecommerce-lite.fullname" . }}
  labels:
    app: {{ include "ecommerce-lite.name" . }}
    release: {{ .Values.serviceMonitor.releaseLabel | default "kube-prometheus-stack" }}
spec:
  selector:
    matchLabels:
      app: {{ include "ecommerce-lite.name" . }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
