apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-lite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Norman0554/ecommerce-lite.git
    targetRevision: main
    path: helm/ecommerce-lite
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-lite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
